"""create patents families table

Revision ID: 66295e20cabf
Revises: 7171f8b78275
Create Date: 2025-04-23 01:37:32.385104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66295e20cabf'
down_revision: Union[str, None] = '7171f8b78275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents_families',
    sa.Column('app_number', sa.String(length=55), nullable=False),
    sa.Column('app_date', sa.DateTime(), nullable=False),
    sa.Column('main_cpc', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('claims', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['main_cpc'], ['cpc.cpc_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_number')
    )

    op.drop_constraint('assignees_groups_patent_number_fkey', 'assignees_groups', type_='foreignkey')
    op.drop_index('ix_assignees_groups_patent_number', table_name='assignees_groups')
    op.drop_column('assignees_groups', 'patent_number')
    op.add_column('assignees_groups', sa.Column('patents_family', sa.String(length=55), nullable=False))
    op.create_foreign_key(None, 'assignees_groups', 'patents_families', ['patents_family'], ['app_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_assignees_groups_patents_family', 'assignees_groups', ['patents_family'], unique=False)
    
    op.drop_constraint('cpc_classifications_patent_number_fkey', 'cpc_classifications', type_='foreignkey')
    op.drop_index('ix_cpc_classifications_patent_number', table_name='cpc_classifications')
    op.drop_column('cpc_classifications', 'patent_number')
    op.add_column('cpc_classifications', sa.Column('patents_family', sa.String(length=55), nullable=False))
    op.create_foreign_key(None, 'cpc_classifications', 'patents_families', ['patents_family'], ['app_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_cpc_classifications_patents_family', 'cpc_classifications', ['patents_family'], unique=False)
   
    op.drop_index('ix_description_patent_number', table_name='descriptions')
    op.drop_constraint('descriptions_patent_number_fkey', 'descriptions', type_='foreignkey')
    op.drop_column('descriptions', 'patent_number')
    op.add_column('descriptions', sa.Column('patents_family', sa.String(length=55), nullable=False))
    op.create_foreign_key(None, 'descriptions', 'patents_families', ['patents_family'], ['app_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_description_patents_family', 'descriptions', ['patents_family'], unique=False)
    
    op.drop_index('ix_inventors_patent_number', table_name='inventors')
    op.drop_constraint('inventors_patent_number_fkey', 'inventors', type_='foreignkey')
    op.drop_column('inventors', 'patent_number')
    op.add_column('inventors', sa.Column('patents_family', sa.String(length=55), nullable=False))
    op.create_foreign_key(None, 'inventors', 'patents_families', ['patents_family'], ['app_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_inventors_patents_family', 'inventors', ['patents_family'], unique=False)
    
    op.drop_index('ix_ipc_classifications_patent_number', table_name='ipc_classifications')
    op.drop_constraint('ipc_classifications_patent_number_fkey', 'ipc_classifications', type_='foreignkey')
    op.drop_column('ipc_classifications', 'patent_number')
    op.add_column('ipc_classifications', sa.Column('patents_family', sa.String(length=55), nullable=False))
    op.create_foreign_key(None, 'ipc_classifications', 'patents_families', ['patents_family'], ['app_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_ipc_classifications_patents_family', 'ipc_classifications', ['patents_family'], unique=False)
    
    op.drop_column('patents', 'abstract')
    op.drop_column('patents', 'title')
    op.drop_column('patents', 'app_date')
    op.drop_column('patents', 'claims')
    op.drop_constraint('patents_main_cpc_fkey', 'patents', type_='foreignkey')
    op.drop_column('patents', 'main_cpc')
    op.add_column('patents', sa.Column('patents_family', sa.String(length=55), nullable=False))
    op.create_foreign_key(None, 'patents', 'patents_families', ['patents_family'], ['app_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_patents_patents_family', 'patents', ['patents_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patents_patents_family', table_name='patents')
    op.drop_constraint(None, 'patents', type_='foreignkey')
    op.drop_column('patents', 'patents_family')
    op.add_column('patents', sa.Column('main_cpc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('patents_main_cpc_fkey', 'patents', 'cpc', ['main_cpc'], ['cpc_code'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('patents', sa.Column('claims', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patents', sa.Column('app_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('patents', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patents', sa.Column('abstract', sa.VARCHAR(), autoincrement=False, nullable=False))
    
    op.drop_index('ix_ipc_classifications_patents_family', table_name='ipc_classifications')
    op.drop_constraint(None, 'ipc_classifications', type_='foreignkey')
    op.drop_column('ipc_classifications', 'patents_family')
    op.add_column('ipc_classifications', sa.Column('patent_number', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
    op.create_foreign_key('ipc_classifications_patent_number_fkey', 'ipc_classifications', 'patents', ['patent_number'], ['patent_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_ipc_classifications_patent_number', 'ipc_classifications', ['patent_number'], unique=False)
    
    op.drop_index('ix_inventors_patents_family', table_name='inventors')
    op.drop_constraint(None, 'inventors', type_='foreignkey')
    op.drop_column('inventors', 'patents_family')
    op.add_column('inventors', sa.Column('patent_number', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
    op.create_foreign_key('inventors_patent_number_fkey', 'inventors', 'patents', ['patent_number'], ['patent_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_inventors_patent_number', 'inventors', ['patent_number'], unique=False)
    
    op.drop_index('ix_description_patents_family', table_name='descriptions')
    op.drop_constraint(None, 'descriptions', type_='foreignkey')
    op.drop_column('descriptions', 'patents_family')
    op.add_column('descriptions', sa.Column('patent_number', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
    op.create_foreign_key('descriptions_patent_number_fkey', 'descriptions', 'patents', ['patent_number'], ['patent_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_description_patent_number', 'descriptions', ['patent_number'], unique=False)
    
    op.drop_index('ix_cpc_classifications_patents_family', table_name='cpc_classifications')
    op.drop_constraint(None, 'cpc_classifications', type_='foreignkey')
    op.drop_column('cpc_classifications', 'patents_family')
    op.add_column('cpc_classifications', sa.Column('patent_number', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
    op.create_foreign_key('cpc_classifications_patent_number_fkey', 'cpc_classifications', 'patents', ['patent_number'], ['patent_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_cpc_classifications_patent_number', 'cpc_classifications', ['patent_number'], unique=False)
    
    op.drop_index('ix_assignees_groups_patents_family', table_name='assignees_groups')
    op.drop_constraint(None, 'assignees_groups', type_='foreignkey')
    op.drop_column('assignees_groups', 'patents_family')
    op.add_column('assignees_groups', sa.Column('patent_number', sa.VARCHAR(length=55), autoincrement=False, nullable=False))
    op.create_foreign_key('assignees_groups_patent_number_fkey', 'assignees_groups', 'patents', ['patent_number'], ['patent_number'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_assignees_groups_patent_number', 'assignees_groups', ['patent_number'], unique=False)
   
    op.drop_table('patents_families')
    # ### end Alembic commands ###
