"""create descriptions citations ipc cpc tables

Revision ID: 67b9b2ef611d
Revises: c2bcbef0084a
Create Date: 2025-04-13 20:41:14.177091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b9b2ef611d'
down_revision: Union[str, None] = 'c2bcbef0084a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpc',
    sa.Column('cpc_code', sa.String(length=20), nullable=False),
    sa.Column('parent_class', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cpc_code')
    )
    op.create_table('ipc',
    sa.Column('ipc_code', sa.String(length=20), nullable=False),
    sa.Column('parent_class', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ipc_code')
    )
    op.create_table('descriptions',
    sa.Column('description_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_number', sa.String(length=55), nullable=False),
    sa.Column('section_name', sa.String(length=20), nullable=False),
    sa.Column('section_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['patent_number'], ['patents.patent_number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('description_id')
    )
    op.create_table('patent_citations',
    sa.Column('citation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_number', sa.String(length=55), nullable=False),
    sa.Column('cited_patent', sa.String(length=55), nullable=False),
    sa.ForeignKeyConstraint(['patent_number'], ['patents.patent_number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patent_citations')
    op.drop_table('descriptions')
    op.drop_table('ipc')
    op.drop_table('cpc')
    # ### end Alembic commands ###
