"""added field date to patent citations

Revision ID: 7171f8b78275
Revises: 08dbdb6586c1
Create Date: 2025-04-19 15:18:59.099045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7171f8b78275'
down_revision: Union[str, None] = '08dbdb6586c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patent_citations', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patent_citations', 'date')
    # ### end Alembic commands ###
