"""create icp and cpc classifications tables

Revision ID: 1700f59571b6
Revises: 67b9b2ef611d
Create Date: 2025-04-14 02:40:15.062659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1700f59571b6'
down_revision: Union[str, None] = '67b9b2ef611d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpc_classifications',
    sa.Column('classification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_number', sa.String(length=55), nullable=False),
    sa.Column('cpc_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cpc_code'], ['cpc.cpc_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patent_number'], ['patents.patent_number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_id')
    )
    op.create_table('ipc_classifications',
    sa.Column('classification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_number', sa.String(length=55), nullable=False),
    sa.Column('ipc_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ipc_code'], ['ipc.ipc_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patent_number'], ['patents.patent_number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipc_classifications')
    op.drop_table('cpc_classifications')
    # ### end Alembic commands ###
