"""Added indexes for remaining tables

Revision ID: 0bea285a1cb4
Revises: 1700f59571b6
Create Date: 2025-04-14 15:01:34.531708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bea285a1cb4'
down_revision: Union[str, None] = '1700f59571b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cpc_code', 'cpc', ['cpc_code'], unique=False)
    op.create_index('ix_description_patent_number', 'descriptions', ['patent_number'], unique=False)
    op.create_index('ix_inventors_patent_number', 'inventors', ['patent_number'], unique=False)
    op.create_index('ix_ipc_code', 'ipc', ['ipc_code'], unique=False)
    op.create_index('ix_citations_patent_number', 'patent_citations', ['patent_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citations_patent_number', table_name='patent_citations')
    op.drop_index('ix_ipc_code', table_name='ipc')
    op.drop_index('ix_inventors_patent_number', table_name='inventors')
    op.drop_index('ix_description_patent_number', table_name='descriptions')
    op.drop_index('ix_cpc_code', table_name='cpc')
    # ### end Alembic commands ###
