"""Initial commit

Revision ID: d8329ebcf507
Revises: 
Create Date: 2025-03-26 23:28:29.332728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8329ebcf507'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('patent_number', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('app_date', sa.DateTime(), nullable=False),
    sa.Column('main_cpc', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('claims', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('patent_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patents')
    # ### end Alembic commands ###
